### ISSUE TITLE
middle column scroll, fix left and right columns

### ISSUE THREAD

**Issue by frnsys** [jdiedrick/whitefragility#39]
we want the far left and far right column to stay static/unmoving/stuck, but the middle text is scrollable.

**Comment by mehan** [comment]
Two notes on this:
- You will likely only want the fixed layout for those columns to kick in at a high breakpoint (i.e. desktop), so that you can still scroll through all of the columns on mobile
- I started trying to implement this using the `affix` CSS property and ran into a compatibility issue with Bootstrap 3.X--there's some documentation on JS fixes [here](http://stackoverflow.com/questions/18683303/bootstrap-3-0-affix-with-list-changes-width).
