### ISSUE TITLE
tweet quote button

### ISSUE THREAD

**Issue by frnsys** [jdiedrick/whitefragility#41]
we want highly tweetable pull quotes from each page on the right column, so if someone could help integrate the twitter API to open a tweet that with the quote and link

**Comment by Zeesy** [comment]
COOL! Great idea. Can the reader select the pull quote, or are they
pre-selected?

**Comment by frnsys** [comment]
I think for now they are pre-selected, but it would be cool to have that highlight-and-tweet feature down the line!

**Comment by outer-space** [comment]
**Intro:** 
- Why is this white man so angry?
- White people in North America live in a social environment that protects and insulates them from race-based stress.
- Whiteness is a location of structural advantage, of race privilege. 

**Triggers:** 
- White Fragility is a state in which even a minimum amount of racial stress becomes intolerable
- These moves include the outward display of emotions such as anger, fear, and guilt

**Comment by outer-space** [comment]
Segregation:
- The first factor leading to White Fragility is the segregated lives which most white people live

Universalism & Individualism:
- Whites are taught to see their perspectives as objective and representative of reality
- Individualism also allows whites to distance themselves from the actions of their racial group...
- ...and demand to be granted the benefit of the doubt, as individuals, in all cases.
- being an individual or being a human outside of a racial group is a privilege only afforded to white people

Entitlement to Racial Comfort:
- whites typically respond as if something is “wrong,” and blame the person or event that triggered the discomfort
- White insistence on racial comfort ensures that racism will not be faced. 
- Whites often confuse comfort with safety [...] what we really mean is that we don’t feel comfortable.

Racial Arrogance:
- Whites generally feel free to dismiss these informed perspectives...
- ....rather than have the humility to acknowledge that they are unfamiliar, reflect on them further, or seek more

Racial Belonging:
- In virtually any situation or image deemed valuable in dominant society, whites belong. 
-  In dominant society, interruption of racial belonging is rare and thus destabilizing and frightening to whites. 
- Whites consistently choose and enjoy racial segregation. 

Psychic Freedom:
- Because race is constructed as residing in people of color, whites don’t bear the social burden of race. 
- Race is for people of color to think about – it is what happens to “them”

Constant Messages:
- one cannot avoid internalizing the message of white superiority, as it is ubiquitous in mainstream culture.

**Comment by outer-space** [comment]
What Does White Fragility Look Like?
- whites invoke the power to choose when, how, and how much to address or challenge racism
- pointing out white advantage will often trigger patterns of confusion, defensiveness and righteous indignation.
- This discourse of victimization also enables whites to avoid responsibility for the racial power and privilege they wield. 

Conclusion:
- it is critical that all white people build the stamina to sustain conscious and explicit engagement with race.
- all are responsible for either perpetuating or transforming that system.
- White racism is ultimately a white problem and the burden for interrupting it belongs to white people

**Comment by outer-space** [comment]
About:
- This website offers an easy-to-read and easy-to-share version of Robin DiAngelo's White Fragility. 
- Print, assemble and distribute your own White Fragility zine: http://w-f.is/zine
- Once upon a time, someone shared this paper. Later, someone else found it useful.

- As the saying goes, talking about race shouldn't be so stressful -_-
